#define TYPE_INT 1
#define TYPE_LONG 2
#define TYPE_BOOL 3
#define TYPE_CHAR 4
#define TYPE_FLOAT 5
#define TYPE_DOUBLE 6
#define TYPE_CONSTANT 7

#define KEYWORD_IF 8
#define KEYWORD_ELSE 9
#define KEYWORD_WHILE 10
#define KEYWORD_DO 11
#define KEYWORD_SWITCH 12
#define KEYWORD_CASE 13
#define KEYWORD_BREAK 14
#define KEYWORD_CONTINUE 15
#define KEYWORD_FOR 16

#define IDENTIFIER 17

#define OPERATOR_PLUS 18
#define OPERATOR_MINUS 19
#define OPERATOR_MULTIPLY 20
#define OPERATOR_DIVIDE 21
#define OPERATOR_ASSIGNMENT 22

#define LOGIC_AND 23
#define LOGIC_OR 24
#define LOGIC_NOT 25

#define RELATION_EQUALS 26
#define RELATION_NOTEQUAL 27
#define RELATION_LESSER 28
#define RELATION_GREATER 29
#define RELATION_LESSEREQUAL 30
#define RELATION_GREATEREQUAL 31

#define SCOPE_BRACEOPEN 32
#define SCOPE_BRACECLOSE 33

#define ARGUMENT_OPENBRACKET 34
#define ARGUMENT_CLOSEBRACKET 35

#define SEMICOLON 36

#define VALUE_INT 37
#define VALUE_FLOAT 38
#define VALUE_BOOL 39
#define VALUE_CHAR 40

#define COLON 41

#define KEYWORD_DEFAULT 42